server:
  port: 8081
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGODB_URI}/${DB_NAME}
  messages:
    basename: i18n/messages, i18n/messages_es
  jwt:
    secret: ${SECRET_KEY}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka/