server:
  port: 8081
spring:
  application:
    name: Authentication Management Service
  data:
    mongodb:
      uri: ${MONGODB_URI}/${DB_NAME}
  messages:
    basename: i18n/messages, i18n/messages_es

consumers:
  users_url: http://localhost:8080/users